# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('order', models.CharField(max_length=255, verbose_name='Заказ')),
                ('summa', models.IntegerField(default=0, verbose_name='Сумма заказа')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 5, 22, 15, 41, 55, 578367), verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
